name: Triage
on: 
  issues:
    types: [opened, closed, milestoned, demilestoned]
  project_card:
    types: [created, deleted]
    
jobs:
  build:
    name: Triage
    runs-on: ubuntu-16.04
    steps:
    - uses: Logerfo/triage-action@0.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
